imports:
    - { resource: parameters.yml }

framework:
    secret: "%secret%"

wk_google_spreadsheet:
    credentials:
        scope: "https://spreadsheets.google.com/feeds"
        client_email: "%google_spreadsheet_client_email%"
        private_key: "%kernel.root_dir%/App/private.key%"
